name: coozy_the_cafe
description: "A new Flutter project."

version: 1.0.0+1

# Using Android Studio Jellyfish | 2023.3.1 Patch 2
# Windows 10 system
# Flutter version: 3.24.3 stable
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.5
  #  go_router: ^14.2.0
  #
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  rxdart: ^0.28.0
  #
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  line_icons: ^2.0.3
  material_design_icons_flutter: ^7.0.7296
  #
  csv: ^6.0.0
  #
  flutter_localization: ^0.2.2
  #
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.0
  #
#  firebase_auth: ^5.1.4
#  firebase_core: ^3.3.0
#  google_sign_in: ^6.2.1
  #
  #  flutter_webview_plugin_ios_android: ^0.3.13+12
  #
  faker: ^2.2.0
  #
  platform_info: ^5.0.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  #
  fluttertoast: ^8.2.8
  another_flushbar: ^1.12.30
  #
  bubble_showcase: ^1.1.0
  cached_network_image: ^3.4.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_colorpicker: ^1.1.0
  duration_picker: ^1.2.0
  #
  animations: ^2.0.11
  animate_to: ^0.1.0
  animated_text_kit: ^4.2.2
  #
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  internet_connection_checker_plus: ^2.5.1
  url_launcher: ^6.3.0
  #
  url_strategy: ^0.3.0
  timeago: ^3.6.1
  translator: ^1.0.0
  #
  intl: ^0.19.0
  uuid: ^4.5.0
  collection: ^1.19.0
  fast_immutable_collections: ^10.2.4
  #
  reorderable_grid_view: ^2.2.8
  scrollable_positioned_list: ^0.3.8
  #
  sqflite: ^2.3.3+2
  #  sqflite_common: ^2.5.4
  #  sqlite3: ^2.4.3
  #
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.2
  fancy_shimmer_image: ^2.0.3
  flutter_spinkit: ^5.2.1
  #
  path_provider: ^2.1.4
  path: ^1.9.0
  lottie: ^3.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  #
  app_settings: ^5.1.1
#  rate_my_app: ^2.2.0
#  store_redirect: ^2.0.2
  feedback: ^3.1.0
  #  Range Slider
  syncfusion_flutter_core: ^27.1.51
  syncfusion_flutter_sliders: ^27.1.51
  syncfusion_flutter_charts: ^27.1.51
  syncfusion_flutter_xlsio: ^27.1.51
  #
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^3.0.1
  timezone: ^0.9.4
  flutter_slidable: ^3.1.0
  #
  flutter_background_service: ^5.0.10

dependency_overrides:
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/locale/
    - assets/images/
    - assets/images/flags/
    - assets/icons/
    - assets/font/
    - assets/lottie/

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/icons/CustomIcon.ttf
    - family: MenuIcons
      fonts:
        - asset: assets/icons/MenuIcons.ttf
    - family: Menu_search
      fonts:
        - asset: assets/icons/Menu_search.ttf
    - family: BwAletaNo10
      fonts:
        - asset: assets/font/BwAletaNo10/BwAletaNo10_ExtraLight.ttf
          weight: 200
        - asset: assets/font/BwAletaNo10/BwAletaNo10_Light.ttf
          weight: 300
        - asset: assets/font/BwAletaNo10/BwAletaNo10_Regular.ttf
          weight: 400
        - asset: assets/font/BwAletaNo10/BwAletaNo10_Medium.ttf
                    #          weight: 500
                   #        - asset: assets/font/BwAletaNo10/BwAletaNo10_SemiBold.ttf
          weight: 600
        - asset: assets/font/BwAletaNo10/BwAletaNo10_Bold.ttf
          weight: 700
        - asset: assets/font/BwAletaNo10/BwAletaNo10_ExtraBold.ttf
          weight: 800
