import 'package:coozy_cafe/routing/routs.dart';
import 'package:flutter/material.dart';

final navigationRoutes = NavigationRoutes.getInstance();

final bucketGlobal = PageStorageBucket();

final GlobalKey<NavigatorState> navigatorKey =
    GlobalKey<NavigatorState>(debugLabel: "navigatorKey");

// Define a list of language objects
List<Map<String, String>> jsonLanguagesData  = [
    {"name": "Afar", "code_2": "aa", "code_3": "aar"},
    {"name": "Abkhazian", "code_2": "ab", "code_3": "abk"},
    {"name": "Avestan", "code_2": "ae", "code_3": "ave"},
    {"name": "Afrikaans", "code_2": "af", "code_3": "afr"},
    {"name": "Akan", "code_2": "ak", "code_3": "aka"},
    {"name": "Amharic", "code_2": "am", "code_3": "amh"},
    {"name": "Aragonese", "code_2": "an", "code_3": "arg"},
    {"name": "Arabic", "code_2": "ar", "code_3": "ara"},
    {"name": "Assamese", "code_2": "as", "code_3": "asm"},
    {"name": "Avaric", "code_2": "av", "code_3": "ava"},
    {"name": "Aymara", "code_2": "ay", "code_3": "aym"},
    {"name": "Azerbaijani", "code_2": "az", "code_3": "aze"},
    {"name": "Bashkir", "code_2": "ba", "code_3": "bak"},
    {"name": "Belarusian", "code_2": "be", "code_3": "bel"},
    {"name": "Bulgarian", "code_2": "bg", "code_3": "bul"},
    {"name": "Bihari languages", "code_2": "bh", "code_3": "bih"},
    {"name": "Bislama", "code_2": "bi", "code_3": "bis"},
    {"name": "Bambara", "code_2": "bm", "code_3": "bam"},
    {"name": "Bengali", "code_2": "bn", "code_3": "ben"},
    {"name": "Tibetan", "code_2": "bo", "code_3": "tib"},
    {"name": "Breton", "code_2": "br", "code_3": "bre"},
    {"name": "Bosnian", "code_2": "bs", "code_3": "bos"},
    {"name": "Catalan; Valencian", "code_2": "ca", "code_3": "cat"},
    {"name": "Chechen", "code_2": "ce", "code_3": "che"},
    {"name": "Chamorro", "code_2": "ch", "code_3": "cha"},
    {"name": "Corsican", "code_2": "co", "code_3": "cos"},
    {"name": "Cree", "code_2": "cr", "code_3": "cre"},
    {"name": "Czech", "code_2": "cs", "code_3": "cze"},
    {"name": "Church Slavic; Slavonic; Old Bulgarian", "code_2": "cu", "code_3": "chu"},
    {"name": "Chuvash", "code_2": "cv", "code_3": "chv"},
    {"name": "Welsh", "code_2": "cy", "code_3": "wel"},
    {"name": "Danish", "code_2": "da", "code_3": "dan"},
    {"name": "German", "code_2": "de", "code_3": "ger"},
    {"name": "Divehi; Dhivehi; Maldivian", "code_2": "dv", "code_3": "div"},
    {"name": "Dzongkha", "code_2": "dz", "code_3": "dzo"},
    {"name": "Ewe", "code_2": "ee", "code_3": "ewe"},
    {"name": "Greek, Modern (1453-)", "code_2": "el", "code_3": "gre"},
    {"name": "English", "code_2": "en", "code_3": "eng"},
    {"name": "Esperanto", "code_2": "eo", "code_3": "epo"},
    {"name": "Spanish; Castilian", "code_2": "es", "code_3": "spa"},
    {"name": "Estonian", "code_2": "et", "code_3": "est"},
    {"name": "Basque", "code_2": "eu", "code_3": "baq"},
    {"name": "Persian", "code_2": "fa", "code_3": "per"},
    {"name": "Fulah", "code_2": "ff", "code_3": "ful"},
    {"name": "Finnish", "code_2": "fi", "code_3": "fin"},
    {"name": "Fijian", "code_2": "fj", "code_3": "fij"},
    {"name": "Faroese", "code_2": "fo", "code_3": "fao"},
    {"name": "French", "code_2": "fr", "code_3": "fre"},
    {"name": "Western Frisian", "code_2": "fy", "code_3": "fry"},
    {"name": "Irish", "code_2": "ga", "code_3": "gle"},
    {"name": "Gaelic; Scottish Gaelic", "code_2": "gd", "code_3": "gla"},
    {"name": "Galician", "code_2": "gl", "code_3": "glg"},
    {"name": "Guarani", "code_2": "gn", "code_3": "grn"},
    {"name": "Gujarati", "code_2": "gu", "code_3": "guj"},
    {"name": "Manx", "code_2": "gv", "code_3": "glv"},
    {"name": "Hausa", "code_2": "ha", "code_3": "hau"},
    {"name": "Hebrew", "code_2": "he", "code_3": "heb"},
    {"name": "Hindi", "code_2": "hi", "code_3": "hin"},
    {"name": "Hiri Motu", "code_2": "ho", "code_3": "hmo"},
    {"name": "Croatian", "code_2": "hr", "code_3": "hrv"},
    {"name": "Haitian; Haitian Creole", "code_2": "ht", "code_3": "hat"},
    {"name": "Hungarian", "code_2": "hu", "code_3": "hun"},
    {"name": "Armenian", "code_2": "hy", "code_3": "arm"},
    {"name": "Herero", "code_2": "hz", "code_3": "her"},
    {"name": "Interlingua", "code_2": "ia", "code_3": "ina"},
    {"name": "Indonesian", "code_2": "id", "code_3": "ind"},
    {"name": "Interlingue; Occidental", "code_2": "ie", "code_3": "ile"},
    {"name": "Igbo", "code_2": "ig", "code_3": "ibo"},
    {"name": "Sichuan Yi; Nuosu", "code_2": "ii", "code_3": "iii"},
    {"name": "Inupiaq", "code_2": "ik", "code_3": "ipk"},
    {"name": "Ido", "code_2": "io", "code_3": "ido"},
    {"name": "Icelandic", "code_2": "is", "code_3": "ice"},
    {"name": "Italian", "code_2": "it", "code_3": "ita"},
    {"name": "Inuktitut", "code_2": "iu", "code_3": "iku"},
    {"name": "Japanese", "code_2": "ja", "code_3": "jpn"},
    {"name": "Javanese", "code_2": "jv", "code_3": "jav"},
    {"name": "Georgian", "code_2": "ka", "code_3": "geo"},
    {"name": "Kongo", "code_2": "kg", "code_3": "kon"},
    {"name": "Kikuyu; Gikuyu", "code_2": "ki", "code_3": "kik"},
    {"name": "Kuanyama; Kwanyama", "code_2": "kj", "code_3": "kua"},
    {"name": "Kazakh", "code_2": "kk", "code_3": "kaz"},
    {"name": "Kalaallisut; Greenlandic", "code_2": "kl", "code_3": "kal"},
    {"name": "Central Khmer", "code_2": "km", "code_3": "khm"},
    {"name": "Kannada", "code_2": "kn", "code_3": "kan"},
    {"name": "Korean", "code_2": "ko", "code_3": "kor"},
    {"name": "Kanuri", "code_2": "kr", "code_3": "kau"},
    {"name": "Kashmiri", "code_2": "ks", "code_3": "kas"},
    {"name": "Kurdish", "code_2": "ku", "code_3": "kur"},
    {"name": "Komi", "code_2": "kv", "code_3": "kom"},
    {"name": "Cornish", "code_2": "kw", "code_3": "cor"},
    {"name": "Kirghiz; Kyrgyz", "code_2": "ky", "code_3": "kir"},
    {"name": "Latin", "code_2": "la", "code_3": "lat"},
    {"name": "Luxembourgish; Letzeburgesch", "code_2": "lb", "code_3": "ltz"},
    {"name": "Ganda", "code_2": "lg", "code_3": "lug"},
    {"name": "Limburgan; Limburger; Limburgish", "code_2": "li", "code_3": "lim"},
    {"name": "Lingala", "code_2": "ln", "code_3": "lin"},
    {"name": "Lao", "code_2": "lo", "code_3": "lao"},
    {"name": "Lithuanian", "code_2": "lt", "code_3": "lit"},
    {"name": "Luba-Katanga", "code_2": "lu", "code_3": "lub"},
    {"name": "Latvian", "code_2": "lv", "code_3": "lav"},
    {"name": "Malagasy", "code_2": "mg", "code_3": "mlg"},
    {"name": "Marshallese", "code_2": "mh", "code_3": "mah"},
    {"name": "Maori", "code_2": "mi", "code_3": "mao"},
    {"name": "Macedonian", "code_2": "mk", "code_3": "mac"},
    {"name": "Malayalam", "code_2": "ml", "code_3": "mal"},
    {"name": "Mongolian", "code_2": "mn", "code_3": "mon"},
    {"name": "Marathi", "code_2": "mr", "code_3": "mar"},
    {"name": "Malay", "code_2": "ms", "code_3": "may"},
    {"name": "Maltese", "code_2": "mt", "code_3": "mlt"},
    {"name": "Burmese", "code_2": "my", "code_3": "bur"},
    {"name": "Nauru", "code_2": "na", "code_3": "nau"},
    {"name": "Norwegian Bokmål", "code_2": "nb", "code_3": "nob"},
    {"name": "Ndebele, North; North Ndebele", "code_2": "nd", "code_3": "nde"},
    {"name": "Nepali", "code_2": "ne", "code_3": "nep"},
    {"name": "Ndonga", "code_2": "ng", "code_3": "ndo"},
    {"name": "Dutch; Flemish", "code_2": "nl", "code_3": "dut"},
    {"name": "Norwegian Nynorsk", "code_2": "nn", "code_3": "nno"},
    {"name": "Norwegian", "code_2": "no", "code_3": "nor"},
    {"name": "Ndebele, South; South Ndebele", "code_2": "nr", "code_3": "nbl"},
    {"name": "Navajo; Navaho", "code_2": "nv", "code_3": "nav"},
    {"name": "Chichewa; Chewa; Nyanja", "code_2": "ny", "code_3": "nya"},
    {"name": "Occitan (post 1500)", "code_2": "oc", "code_3": "oci"},
    {"name": "Ojibwa", "code_2": "oj", "code_3": "oji"},
    {"name": "Oromo", "code_2": "om", "code_3": "orm"},
    {"name": "Oriya", "code_2": "or", "code_3": "ori"},
    {"name": "Ossetian; Ossetic", "code_2": "os", "code_3": "oss"},
    {"name": "Panjabi; Punjabi", "code_2": "pa", "code_3": "pan"},
    {"name": "Pali", "code_2": "pi", "code_3": "pli"},
    {"name": "Polish", "code_2": "pl", "code_3": "pol"},
    {"name": "Pushto; Pashto", "code_2": "ps", "code_3": "pus"},
    {"name": "Portuguese", "code_2": "pt", "code_3": "por"},
    {"name": "Quechua", "code_2": "qu", "code_3": "que"},
    {"name": "Romansh", "code_2": "rm", "code_3": "roh"},
    {"name": "Rundi", "code_2": "rn", "code_3": "run"},
    {"name": "Romanian; Moldavian; Moldovan", "code_2": "ro", "code_3": "rum"},
    {"name": "Russian", "code_2": "ru", "code_3": "rus"},
    {"name": "Kinyarwanda", "code_2": "rw", "code_3": "kin"},
    {"name": "Sanskrit", "code_2": "sa", "code_3": "san"},
    {"name": "Sardinian", "code_2": "sc", "code_3": "srd"},
    {"name": "Sindhi", "code_2": "sd", "code_3": "snd"},
    {"name": "Northern Sami", "code_2": "se", "code_3": "sme"},
    {"name": "Sango", "code_2": "sg", "code_3": "sag"},
    {"name": "Sinhala; Sinhalese", "code_2": "si", "code_3": "sin"},
    {"name": "Slovak", "code_2": "sk", "code_3": "slo"},
    {"name": "Slovenian", "code_2": "sl", "code_3": "slv"},
    {"name": "Samoan", "code_2": "sm", "code_3": "smo"},
    {"name": "Shona", "code_2": "sn", "code_3": "sna"},
    {"name": "Somali", "code_2": "so", "code_3": "som"},
    {"name": "Albanian", "code_2": "sq", "code_3": "alb"},
    {"name": "Serbian", "code_2": "sr", "code_3": "srp"},
    {"name": "Swati", "code_2": "ss", "code_3": "ssw"},
    {"name": "Sotho, Southern", "code_2": "st", "code_3": "sot"},
    {"name": "Sundanese", "code_2": "su", "code_3": "sun"},
    {"name": "Swedish", "code_2": "sv", "code_3": "swe"},
    {"name": "Swahili", "code_2": "sw", "code_3": "swa"},
    {"name": "Tamil", "code_2": "ta", "code_3": "tam"},
    {"name": "Telugu", "code_2": "te", "code_3": "tel"},
    {"name": "Tajik", "code_2": "tg", "code_3": "tgk"},
    {"name": "Thai", "code_2": "th", "code_3": "tha"},
    {"name": "Tigrinya", "code_2": "ti", "code_3": "tir"},
    {"name": "Turkmen", "code_2": "tk", "code_3": "tuk"},
    {"name": "Tagalog", "code_2": "tl", "code_3": "tgl"},
    {"name": "Tswana", "code_2": "tn", "code_3": "tsn"},
    {"name": "Tonga (Tonga Islands)", "code_2": "to", "code_3": "ton"},
    {"name": "Turkish", "code_2": "tr", "code_3": "tur"},
    {"name": "Tsonga", "code_2": "ts", "code_3": "tso"},
    {"name": "Tatar", "code_2": "tt", "code_3": "tat"},
    {"name": "Twi", "code_2": "tw", "code_3": "twi"},
    {"name": "Tahitian", "code_2": "ty", "code_3": "tah"},
    {"name": "Uighur; Uyghur", "code_2": "ug", "code_3": "uig"},
    {"name": "Ukrainian", "code_2": "uk", "code_3": "ukr"},
    {"name": "Urdu", "code_2": "ur", "code_3": "urd"},
    {"name": "Uzbek", "code_2": "uz", "code_3": "uzb"},
    {"name": "Venda", "code_2": "ve", "code_3": "ven"},
    {"name": "Vietnamese", "code_2": "vi", "code_3": "vie"},
    {"name": "Volapük", "code_2": "vo", "code_3": "vol"},
    {"name": "Walloon", "code_2": "wa", "code_3": "wln"},
    {"name": "Wolof", "code_2": "wo", "code_3": "wol"},
    {"name": "Xhosa", "code_2": "xh", "code_3": "xho"},
    {"name": "Yiddish", "code_2": "yi", "code_3": "yid"},
    {"name": "Yoruba", "code_2": "yo", "code_3": "yor"},
    {"name": "Zhuang; Chuang", "code_2": "za", "code_3": "zha"},
    {"name": "Chinese", "code_2": "zh", "code_3": "chi"},
    {"name": "Zulu", "code_2": "zu", "code_3": "zul"}
];


