import 'package:coozy_cafe/routing/routs.dart';
import 'package:flutter/material.dart';

final navigationRoutes = NavigationRoutes.getInstance();

final bucketGlobal = PageStorageBucket();

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>(debugLabel: "navigatorKey");

// Define a list of language objects
List<Map<String, String>> jsonLanguagesData = [
    {"name": "Afrikaans", "code_2": "af"},
    {"name": "Albanian", "code_2": "sq"},
    {"name": "Amharic", "code_2": "am"},
    {"name": "Arabic", "code_2": "ar"},
    {"name": "Armenian", "code_2": "hy"},
    {"name": "Assamese", "code_2": "as"},
    {"name": "Aymara", "code_2": "ay"},
    {"name": "Azerbaijani", "code_2": "az"},
    {"name": "Bambara", "code_2": "bm"},
    {"name": "Basque", "code_2": "eu"},
    {"name": "Belarusian", "code_2": "be"},
    {"name": "Bengali", "code_2": "bn"},
    {"name": "Bhojpuri", "code_2": "bho"},
    {"name": "Bosnian", "code_2": "bs"},
    {"name": "Bulgarian", "code_2": "bg"},
    {"name": "Catalan", "code_2": "ca"},
    {"name": "Cebuano", "code_2": "ceb"},
    {"name": "Chinese (Simplified)", "code_2": "zh-cn"},
    {"name": "Chinese (Traditional)", "code_2": "zh-tw"},
    {"name": "Corsican", "code_2": "co"},
    {"name": "Croatian", "code_2": "hr"},
    {"name": "Czech", "code_2": "cs"},
    {"name": "Danish", "code_2": "da"},
    {"name": "Dhivehi", "code_2": "dv"},
    {"name": "Dogri", "code_2": "doi"},
    {"name": "Dutch", "code_2": "nl"},
    {"name": "English", "code_2": "en"},
    {"name": "Esperanto", "code_2": "eo"},
    {"name": "Estonian", "code_2": "et"},
    {"name": "Ewe", "code_2": "ee"},
    {"name": "Filipino (Tagalog)", "code_2": "fil"},
    {"name": "Finnish", "code_2": "fi"},
    {"name": "French", "code_2": "fr"},
    {"name": "Frisian", "code_2": "fy"},
    {"name": "Galician", "code_2": "gl"},
    {"name": "Georgian", "code_2": "ka"},
    {"name": "German", "code_2": "de"},
    {"name": "Greek", "code_2": "el"},
    {"name": "Guarani", "code_2": "gn"},
    {"name": "Gujarati", "code_2": "gu"},
    {"name": "Haitian Creole", "code_2": "ht"},
    {"name": "Hausa", "code_2": "ha"},
    {"name": "Hawaiian", "code_2": "haw"},
    {"name": "Hebrew", "code_2": "he"},
    {"name": "Hindi", "code_2": "hi"},
    {"name": "Hmong", "code_2": "hmn"},
    {"name": "Hungarian", "code_2": "hu"},
    {"name": "Icelandic", "code_2": "is"},
    {"name": "Igbo", "code_2": "ig"},
    {"name": "Ilocano", "code_2": "ilo"},
    {"name": "Indonesian", "code_2": "id"},
    {"name": "Irish", "code_2": "ga"},
    {"name": "Italian", "code_2": "it"},
    {"name": "Japanese", "code_2": "ja"},
    {"name": "Javanese", "code_2": "jv"},
    {"name": "Kannada", "code_2": "kn"},
    {"name": "Kazakh", "code_2": "kk"},
    {"name": "Khmer", "code_2": "km"},
    {"name": "Kinyarwanda", "code_2": "rw"},
    {"name": "Konkani", "code_2": "gom"},
    {"name": "Korean", "code_2": "ko"},
    {"name": "Krio", "code_2": "kri"},
    {"name": "Kurdish (Kurmanji)", "code_2": "ku"},
    {"name": "Kurdish (Sorani)", "code_2": "ckb"},
    {"name": "Kyrgyz", "code_2": "ky"},
    {"name": "Lao", "code_2": "lo"},
    {"name": "Latin", "code_2": "la"},
    {"name": "Latvian", "code_2": "lv"},
    {"name": "Lingala", "code_2": "ln"},
    {"name": "Lithuanian", "code_2": "lt"},
    {"name": "Luganda", "code_2": "lg"},
    {"name": "Luxembourgish", "code_2": "lb"},
    {"name": "Macedonian", "code_2": "mk"},
    {"name": "Maithili", "code_2": "mai"},
    {"name": "Malagasy", "code_2": "mg"},
    {"name": "Malay", "code_2": "ms"},
    {"name": "Malayalam", "code_2": "ml"},
    {"name": "Maltese", "code_2": "mt"},
    {"name": "Maori", "code_2": "mi"},
    {"name": "Marathi", "code_2": "mr"},
    {"name": "Meiteilon (Manipuri)", "code_2": "mni-mtei"},
    {"name": "Mizo", "code_2": "lus"},
    {"name": "Mongolian", "code_2": "mn"},
    {"name": "Myanmar (Burmese)", "code_2": "my"},
    {"name": "Nepali", "code_2": "ne"},
    {"name": "Norwegian", "code_2": "no"},
    {"name": "Nyanja (Chichewa)", "code_2": "ny"},
    {"name": "Odia (Oriya)", "code_2": "or"},
    {"name": "Oromo", "code_2": "om"},
    {"name": "Pashto", "code_2": "ps"},
    {"name": "Persian", "code_2": "fa"},
    {"name": "Polish", "code_2": "pl"},
    {"name": "Portuguese", "code_2": "pt"},
    {"name": "Punjabi", "code_2": "pa"},
    {"name": "Quechua", "code_2": "qu"},
    {"name": "Romanian", "code_2": "ro"},
    {"name": "Russian", "code_2": "ru"},
    {"name": "Samoan", "code_2": "sm"},
    {"name": "Sanskrit", "code_2": "sa"},
    {"name": "Scots Gaelic", "code_2": "gd"},
    {"name": "Sepedi", "code_2": "nso"},
    {"name": "Serbian", "code_2": "sr"},
    {"name": "Sesotho", "code_2": "st"},
    {"name": "Shona", "code_2": "sn"},
    {"name": "Sindhi", "code_2": "sd"},
    {"name": "Sinhala", "code_2": "si"},
    {"name": "Slovak", "code_2": "sk"},
    {"name": "Slovenian", "code_2": "sl"},
    {"name": "Somali", "code_2": "so"},
    {"name": "Spanish", "code_2": "es"},
    {"name": "Sundanese", "code_2": "su"},
    {"name": "Swahili", "code_2": "sw"},
    {"name": "Swedish", "code_2": "sv"},
    {"name": "Tagalog (Filipino)", "code_2": "tl"},
    {"name": "Tajik", "code_2": "tg"},
    {"name": "Tamil", "code_2": "ta"},
    {"name": "Tatar", "code_2": "tt"},
    {"name": "Telugu", "code_2": "te"},
    {"name": "Thai", "code_2": "th"},
    {"name": "Tigrinya", "code_2": "ti"},
    {"name": "Tsonga", "code_2": "ts"},
    {"name": "Turkish", "code_2": "tr"},
    {"name": "Turkmen", "code_2": "tk"},
    {"name": "Twi (Akan)", "code_2": "ak"},
    {"name": "Ukrainian", "code_2": "uk"},
    {"name": "Urdu", "code_2": "ur"},
    {"name": "Uyghur", "code_2": "ug"},
    {"name": "Uzbek", "code_2": "uz"},
    {"name": "Vietnamese", "code_2": "vi"},
    {"name": "Welsh", "code_2": "cy"},
    {"name": "Xhosa", "code_2": "xh"},
    {"name": "Yiddish", "code_2": "yi"},
    {"name": "Yoruba", "code_2": "yo"},
    {"name": "Zulu", "code_2": "zu"},
];

