/// Flutter icons MenuIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcons
///      fonts:
///       - asset: fonts/MenuIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MenuIcons {
  MenuIcons._();

  static const _kFontFam = 'MenuIcons';
  static const String? _kFontPkg = null;

  static const IconData round_table = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData menu_placeholder =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData menu_empty_paceholder =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check_list = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData serving_time = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData coooking_time = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData total_cooking_time =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData recipe_book_icon =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData recipe = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData recipe_cooking_book =
      IconData(0xe809, fontFamily: _kFontFam);
}
