/// Flutter icons Menu_search
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Menu_search
///      fonts:
///       - asset: fonts/Menu_search.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Menu_search {
  Menu_search._();

  static const _kFontFam = 'Menu_search';
  static const String? _kFontPkg = null;

  static const IconData menu_search = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData fill_order_add_btn = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData order_border_add_btn = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
}
